[package]
name = "rust_lib"
version = "0.1.0"
authors = ["jon-smith"]
edition = "2021"

[dependencies]
cxx = "1.0"
anyhow = "1.0"
reqwest = { version = "0.12", features = ["json", "blocking", "native-tls-vendored"] }

[build-dependencies]
cxx-build = "1.0"

[lib]
crate-type = ["staticlib"]
