name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-latest]
        include:
          - os: ubuntu-24.04
            compiler: gcc
          - os: windows-latest
            compiler: msvc-x64

    runs-on: ${{ matrix.os }}

    name: Build ${{ matrix.os }} ${{ matrix.compiler }}

    env:
      PRESET: ${{ matrix.compiler }}-release

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Config
        run: cmake --preset $PRESET

      - name: Build
        run: cmake --build out/build/$PRESET

      - name: Run
        run: out/build/$PRESET/src/rust_cxx_cmake
